#!/bin/bash
# Generates a README.md file describing all sibling scripts, through the parsing
# of each script header

FILE_NAME="README.md"
SCRIPTS=`find "$PWD" -maxdepth 2 | grep '\.sh'`

print-script-parameters() {
  parameters=$(
    printf "$1" | grep '^\$' | awk '{printf "**%s**  \n",$0} END {print ""}'
  )
  [[ ! -z "$parameters" ]] && printf "$parameters  \n  \n"
}

print-see-readme() {
  readme_path="`dirname $1`/README.md"
  [[ -f "$readme_path" ]] &&
  [[ "$(dirname $readme_path)" != "$(dirname $FILE_NAME)" ]] &&
  printf "  \n>See [README.md]($readme_path)  \n  \n"
}

echo "\
# Shell Scripts
### This file is automatically generated by \``basename "$0"`\` script, \
triggered by a local git hook.
" > "$FILE_NAME"

for script in $SCRIPTS; do
  script_name=`echo $script | sed "s|$(pwd)/||"`
  script_header=$(sed '/^#!/d;/^$/q;s/^# //' $script)
  script_description=$(printf "$script_header" | grep -v '^\$')
echo "\
## \`$script_name\`

- $script_description  
`print-script-parameters "$script_header"`\
`print-see-readme "$script_name"`\
" >> "$FILE_NAME"
done