#!/bin/bash
# Generates a README.md file describing all sibling scripts, through the parsing
# of each script header

FILE_NAME="README.md"
SCRIPTS=`find "$PWD" | grep '\.sh'`
SCRIPT_HEADER=""
SCRIPT_DESCRIPTION=""
SCRIPT_PARAMETERS=""

# $1: script path
parse-script() {
  SCRIPT_HEADER=$(sed '/^#!/d;/^$/q;s/^# //' $1)
  SCRIPT_DESCRIPTION=$(printf "$SCRIPT_HEADER" | grep -v '^\$')
  SCRIPT_PARAMETERS=$(
    printf "$SCRIPT_HEADER" | grep '^\$' | 
    awk '{printf "**%s**  \n",$0} END {print ""}'
  )
}

echo "\
# Shell Scripts
## This file is automatically generated by \``basename "$0"`\` through a git hook.
" > "$FILE_NAME"

for script in $SCRIPTS; do
  parse-script $script
  script_name=`basename "$script"`
echo "\
## \`$script_name\`
>`basename $(dirname $script)`/$script_name
- $SCRIPT_DESCRIPTION  
$SCRIPT_PARAMETERS\
" >> "$FILE_NAME"
done